# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  slack: circleci/slack@4.5.1
  node: circleci/node@4.9.0
jobs:
  build_deploy_stg:
    executor:
      name: node/default
      tag: ‘12.19.0’
    steps:
      - checkout
      - node/install-yarn
      - run:
          name: "Build"
          command: yarn build
workflows:
  say-hello-workflow:
    jobs:
      - build_deploy_stg
